apiVersion: v1
kind: Service
metadata:
  name: trafficmgmt-rabbitmq-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: trafficmgmt-rabbitmq-container