apiVersion: v1
kind: ConfigMap
metadata:
  name: trafficmgmt-configmap
data:
  POSTGRES_DB: 'traffic_mgmt'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'pass1234'
  POSTGRES_HOST: 'trafficmgmt-postgres-service'
  POSTGRES_PORT: '5432'
  CELERYAPP_HOST: 'trafficmgmt-celeryapp-service'
  RABBITMQ_HOST: 'amqps-uri'
  RABBITMQ_QUEUE: 'traffic_mgmt'
  OPENAI_API_KEY: 'api-key'
