kind: Service
apiVersion: v1
metadata:
  name: trafficmgmt-postgres-service
spec:
  selector:
    app: trafficmgmt-postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
