apiVersion: v1
kind: Service
metadata:
  name: trafficmgmt-redis-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: trafficmgmt-redis-container