apiVersion: v1
kind: Service
metadata:
  name: controlpanel-redis-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: controlpanel-redis-container