apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-redis-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlpanel-redis-container
  template:
    metadata:
      labels:
        app: controlpanel-redis-container
    spec:
      containers:
      - name: redis
        image: redis:latest
        command: ["redis-server"]
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
