apiVersion: batch/v1
kind: Job
metadata:
  name: controlpanel-django-loaddata
spec:
  template:
    spec:
      containers:
        - name: controlpanel-django-loaddata
          image: quay.io/aenvsite/control_panel
          command: ['python', 'manage.py', 'reset_dev']
          envFrom:
          - configMapRef:
              name: controlpanel-configmap
      restartPolicy: Never
  backoffLimit: 5