apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: controlpanel-celeryapp-container
  name: controlpanel-celeryapp-container
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controlpanel-celeryapp-container
        component: controlpanel-celeryapp-container
    spec:
      containers:
      - image: quay.io/aenvsite/control_panel
        name: controlpanel-celeryapp-container
        command: [ "/bin/sh","-c" ]
        args: [ "celery -A web_app worker -l info;" ]
        envFrom:
        - configMapRef:
            name: controlpanel-configmap
