apiVersion: v1
kind: Service
metadata:
  name: controlpanel-rabbitmq-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: controlpanel-rabbitmq-container