apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-rabbitmq-container
  labels:
    app: controlpanel-rabbitmq-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controlpanel-rabbitmq-container
  template:
    metadata:
      labels:
        app: controlpanel-rabbitmq-container
    spec:
      containers:
        - name: controlpanel-rabbitmq-container
          image: quay.io/aenvsite/control_panel
          command: [ "/bin/sh","-c" ]
          args: [ "python rabbitmq_consumer.py;" ]
          envFrom:
          - configMapRef:
              name: controlpanel-configmap
